#! /bin/bash
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr -config server.conf -extensions SAN
openssl x509 -req -days 3650 -in server.csr -signkey server.key \
  -out server.crt -extfile server.conf -extensions SAN
